spring:
  jda:
    auto-create: true
    token: NDIzMTk5NzY3MDI4MzAxODI0.Wqglfw.QHwghaR4_zjgY5tRzWipArBpR2Q
    activity:
      type: listening
      activity: Курсы о self-development

logging:
  level:
    ROOT: INFO
    love.korni: TRACE